Added spurious correlation feature summary to the report section of datalab
cleanlab/cleanlab pull request #1171
Opened 2024-07-05 04:54 UTC by allincowell

## Summary

> Added Spurious Correlations of image-specific features like `dark_score`, `blurry_score`, etc. to `lab.report()` and highlighting the minimum and maximum individual instances in the dataset for each correlated feature.

## Example Usage
```python

from cleanlab import Datalab

lab = Datalab(data=dataset, label_name="label", image_key="image")
lab.find_issues()
lab.report()
```

## Links to Relevant Issues or Conversations

> Earlier related PR: https://github.com/cleanlab/cleanlab/pull/1140

2024-07-06 06:58 UTC, jwmueller commented
Could you update the PR description to include: 
- what the output of the code snippet looks like for a dataset with known spurious correlation
- what the output of the code snippet looks like for a dataset known to have no spurious correlation
- what tests/benchmarks you ran to ensure this code works across different types of datasets

Thanks!

2024-07-23 02:55 UTC, elisno commented
I've made an update to the workflow tutorial.

The code looks fine, but needs more testing.
@allincowell, can you ensure that the reporting code gets better coverage?
1. One test to ensure that for a detected spurious correlation, it should be shown in the report.
2. Another test to ensure that when no spurious correlation is detected, the report shouldn't show anything related to spurious correlations.

2024-07-23 02:57 UTC, elisno requested changes
Please improve the test coverage of this PR.

2024-07-23 02:57 UTC, elisno commented on cleanlab/datalab/internal/adapter/imagelab.py
> +
These lines need test coverage, as this is all new code.
When will it run and when shouldn't it run?

2024-07-30 16:25 UTC, elisno approved these changes
LGTM!

2024-07-30 16:27 UTC, merged