Added support for returning ranked issue idxs
cleanlab/cleanlab pull request #459
Opened 2022-09-16 21:58 UTC by ulya-tkch

- code
- tests
- docstring

2022-09-16 22:00 UTC, jwmueller commented on cleanlab/rank.py
> +def find_top_issues(quality_scores, top=20):
add types ?

2022-09-16 22:03 UTC, elisno commented on cleanlab/rank.py
> +    """
```suggestion
def find_top_issues(quality_scores: np.ndarray, top:  Optional[int]=20) -> np.ndarray:
    """
    Uses passed in `quality_scores` to return `top` indices corresponding to examples most likely to be issues.
    Indices ordered from most to least likely to be an issue based on value of quality_score.

    Parameters
    ----------
    quality_scores : 
      Scores array of shape ``(N,)``, where N is the number of examples.

    top :
      The number of top scores to return.

    Returns
    -------
    top_issue_indices :
      Top indices of issue examples ranked by how likely they are to be an issue.
    """
```

2022-09-16 22:26 UTC, jwmueller approved these changes
LGTM!

2022-09-16 22:30 UTC, jwmueller commented on cleanlab/rank.py
> +    Indices ordered from most to least likely to be an issue based on value of quality_score.
```suggestion
    Uses provided `quality_scores` to return `top` indices corresponding to the examples most likely to exhibit issues of a particular type.
    Returned indices are ordered from most to least severe instance of issue (based on value of `quality_score`). 
    Make sure that the ordering of `quality_scores` matches the examples in your dataset.
```

2022-09-16 22:31 UTC, jwmueller commented on cleanlab/rank.py
> +      Scores array of shape ``(N,)``, where N is the number of examples.
```suggestion
      Array of shape ``(N,)``, where N is the number of examples, containing one quality score for each example in the dataset.
```

2022-09-16 22:31 UTC, jwmueller commented on cleanlab/rank.py
> +      The number of top scores to return.
```suggestion
      The number of indices to return.
```

2022-09-16 22:33 UTC, jwmueller commented on cleanlab/rank.py
> +      Top indices of issue examples ranked by how likely they are to be an issue.
```suggestion
      Indices of top examples most likely to suffer from issue (ranked by issue severity). 
```

2022-09-16 22:34 UTC, jwmueller commented on cleanlab/outlier.py
> +    To get indices of examples that are most likely outliers call :py:func:`find_top_issues <cleanlab.rank.find_top_issues>` function on computed OOD scores.
```suggestion
    To get indices of examples that are the most severe outliers, call :py:func:`find_top_issues <cleanlab.rank.find_top_issues>` method on the returned OOD scores.
```

2022-09-16 23:01 UTC, elisno requested changes

2022-09-16 23:01 UTC, elisno commented on cleanlab/rank.py
> +      Indices of top examples most likely to suffer from issue (ranked by issue severity).
```suggestion
      Indices of top examples most likely to suffer from an issue (ranked by issue severity). 
```

2022-09-16 23:11 UTC, jwmueller commented on tests/test_rank.py
> +    top_outlier_indices_more_k = rank.find_top_issues(quality_scores=ood_scores, top=100000)
```suggestion
    top_outlier_indices_more_k = rank.find_top_issues(ood_scores, top=100000)
```

2022-09-16 23:16 UTC, jwmueller commented on tests/test_rank.py
> +    top_outlier_indices_more_k = rank.find_top_issues(quality_scores=ood_scores, top=100000)
maybe also good to sometimes test positional args are truly positional as I suggested above, now that we commonly use `,*,` in the function signatures

2022-09-16 23:16 UTC, jwmueller commented on cleanlab/rank.py
> +def find_top_issues(quality_scores: np.ndarray, top: int = 20) -> np.ndarray:
```suggestion
def find_top_issues(quality_scores: np.ndarray, *, top: int = 20) -> np.ndarray:
```

2022-09-16 23:16 UTC, jwmueller commented on cleanlab/rank.py
> +def find_top_issues(quality_scores: np.ndarray, top: int = 20) -> np.ndarray:
this suggestion would make it easier to update signature in the future without breaking API

2022-09-17 00:51 UTC, cgnorthcutt reviewed
change default top=10 from 20. clean up tests

2022-09-17 02:45 UTC, jwmueller approved these changes
LGTM! Will merge after CI queue frees up as we first want to see if docs have been fixed but there are too many Actions Workflows atm

2022-09-17 03:20 UTC, merged