Adds Null Issue Manager
cleanlab/cleanlab pull request #856
Opened 2023-10-03 18:32 UTC by abhijitpal1247

Addresses #810

Made a basic IssueManager for handling null values.

2023-10-03 18:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cleanlab/cleanlab?pullRequest=856) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cleanlab/cleanlab?pullRequest=856) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cleanlab/cleanlab?pullRequest=856) it.</sub>

2023-10-08 05:53 UTC, abhijitpal1247 commented
inputs:

embeddings:
`[[       nan 0.95071431 0.73199394], [0.59865848 0.15601864 0.15599452], [0.05808361        nan 0.60111501], [0.70807258 0.02058449 0.96990985]]`

outputs:

report:

```
----------------------- null issues ------------------------

Number of examples with this issue: 2
Overall dataset quality in terms of this issue: 0.0000

Examples representing most severe instances of this issue:
   is_null_issue  null_score
0           True         0.0
1          False         0.0
2           True         0.0
3          False         0.0

Additional Information: 
average_null_score: 0.0
```

issues:

`[{'is_null_issue': True, 'null_score': 0.0}, {'is_null_issue': False, 'null_score': 0.0}, {'is_null_issue': True, 'null_score': 0.0}, {'is_null_issue': False, 'null_score': 0.0}]`

summary:

`[{'issue_type': 'null', 'score': 0.0}]`

info:

`{'average_null_score': 0.0}`

P.S.: Converted dataframes to dict and presented here

2023-10-10 13:25 UTC, jwmueller requested changes
The quality score for each row should be the fraction of features which are not null in that row.

The rows that are marked as `is_null_issue` should ONLY be those rows which are 100% null values.

2023-10-11 01:15 UTC, elisno reviewed
Great work @abhijitpal1247!

I suggest you extract the core logic of computing the issue masks and scores into a separate method (see comment).

I also suggest you compute additional information in `collect_info`.

Finally, I suggest you split the "parametrized" embeddings into separate test classes. One without null values, another with some null values.

2023-10-11 01:15 UTC, elisno commented on cleanlab/datalab/internal/issue_manager/null.py
> +        2: [],
I've suggested additional information to store. I suggest you include them at higher verbosity levels.

Say, both at level 1.

2023-10-14 18:28 UTC, jwmueller commented
@elisno will leave this for your review. The main criteria to ensure are simply that:

- The quality score for each row should be the fraction of features which are not null in that row.
- The rows that are marked as is_null_issue should ONLY be those rows which are 100% null values.

2023-10-18 05:23 UTC, abhijitpal1247 commented
@elisno I have implemented the suggested changes. Let me know if I am missing out on something.

2023-10-25 19:53 UTC, abhijitpal1247 commented
@elisno , I have added the changes. Please review it. As we are nearing to the end of hacktoberfest, I would love to get this merge too.

2023-10-27 13:00 UTC, abhijitpal1247 commented
Hey @jwmueller any updates :sweat_smile: We are very close towards the end of hacktoberfest

2023-10-27 14:34 UTC, elisno commented
Hi @abhijitpal1247, I'm pushing a few changes in a bit before we can merge this today!

2023-10-30 02:40 UTC, elisno approved these changes
Wonderful work @abhijitpal1247!
Thank you for adding this issue manager!

2023-10-30 02:42 UTC, merged